### ISSUE TITLE
Update to 1.16.2

### ISSUE THREAD

**Issue by official-markus-maurer** [KubeJS-Mods/KubeJS-Fabric#6]
I really enjoy the mod and hope it gets updated to 1.16.2 👍

**Comment by vini2003** [comment]
We'll update it soon, just that me and @shedaniel are prioritizing anime at the moment.

**Comment by official-markus-maurer** [comment]
> We'll update it soon, just that me and @shedaniel are prioritizing anime at the moment.

ありがとうございました、for the great effort, as a man of culture, I can relate.
